Mappings:
  RegionMap:
    us-east-1:
      AMI: ami-0922553b7b0369273
    us-west-1:
      AMI: ami-bf5540df
    eu-west-1:
      AMI: ami-3bfab942
    ap-southeast-1:
      AMI: ami-e2adf99e
    ap-southeast-2:
      AMI: ami-43874721
      
Resources: 
  MyEc2Instance: 
    Type: AWS::EC2::Instance
    Properties: 
      InstanceType: t2.micro
      KeyName: zhongz
      ImageId: 
        Fn::FindInMap:
        - RegionMap
        - !Ref AWS::Region
        - AMI
      SecurityGroups: 
        - !Ref MySecurityGroup
      Tags: 
        - Key: name
          Value: !Join [" ",[this is my test instance] ]
          
  MySecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable SSH access via port 22
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0